src/Entity/Messages.php
<?php

namespace App\Entity;

use App\Repository\MessagesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: MessagesRepository::class)]
class Messages
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $message = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE,  options: ["default" => "CURRENT_TIMESTAMP"])]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column(type: 'boolean', options: ['default' => '0'])]
    private ?bool $is_read = null;

    #[ORM\ManyToOne(inversedBy: 'sent')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $sender = null;

    #[ORM\ManyToOne(inversedBy: 'received')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $recipient = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function isIsRead(): ?bool
    {
        return $this->is_read;
    }

    public function setIsRead(bool $is_read): self
    {
        $this->is_read = $is_read;

        return $this;
    }

    public function getSender(): ?User
    {
        return $this->sender;
    }

    public function setSender(?User $sender): self
    {
        $this->sender = $sender;

        return $this;
    }

    public function getRecipient(): ?User
    {
        return $this->recipient;
    }

    public function setRecipient(?User $recipient): self
    {
        $this->recipient = $recipient;

        return $this;
    }

    public function __toString()
    {
        return $this->message;
    }
}

templates/profil/_acheteur.html.twig
<div class="card-seller">
    <h2>Espace acheteur</h2>
    <ul class="flex flex-col gap">
        <h3>Vos commandes</h3>
        {% if commandeAcheteur is not empty %}

        {% for commande in commandeAcheteur %}
        {% if commande.produit.isSelling == true %}
        <li class="card-command flex wrap items-center gap05">

            {% if commande.produit.images is not empty %}
            <!--récupérer la 1er image uniquement -->
            {% set image = commande.produit.images.first() %}
            <img src="{{ asset('uploads/images/' ~ image.nomImage) }}" height="150px" width="100px"
                alt="Image de {{ image.nomImage }}" />

            {% else %}
            <img src="{{ asset('uploads/images/defaut.jpg') }}" height="150px" width="100px" alt="Mon image" />
            {% endif %}

            <div class="grow wrap p-05-w">
                <div class="flex justify-between">
                    <p> {{ commande.produit.nomProduit }}</p>
                    <p> {{ commande.produit.prix}}€</p>
                </div>
                <div class="flex justify-between wrap">
                    <p>Vendeur: {{ commande.produit.user.pseudo }}</p>
                    <div class="flex wrap gap05">
                        <p>Envoi: </p>
                        {% if commande.isSent == false %}
                        <p style="color: #A58AFF">En cours</p>
                        {% else %}
                        <p style="color:green">ok</p>
                        {% endif %}
                    </div>
                </div>
                <div class="flex wrap gap05 justify-between">
                    <div class="flex gap05">
                        <p class="tooltip-container">Produit reçu (?)
                            <span class="tooltip">Penser à cliquer sur le lien une fois que vous avez reçu le
                                colis.</span>
                        </p>
                        <div>
                            {% if commande.isReceived == false %}
                            <a href="{{path('order_received', {'id': commande.id })}}">
                                <p style="color: red;">Non</p>
                            </a>
                            {% else %}
                            <p style="color: green;">Oui</p>
                            {% endif %}

                        </div>
                    </div>
                    <a href="{{path('add_avis', {'vendorId': commande.produit.user.id })}}">Laisser un commentaire</a>
                </div>
            </div>
        </li>
        {% endif %}
        {% endfor %}

        {% else %}
        <p>Aucune commande en cours</p>
        {% endif %}
    </ul>

    <div class="offer-container">
        <h3>Offre émise</h3>
        {% set offreTrouvee = false %}
        {% if offres is empty %}
        <p>Aucune offre émise.</p>
        {% else %}
        <ul class="flex wrap gap">
            {% for offre in offres %}
            {% if offre.isDeleted == 0 and app.user == offre.Users %}
            {% set offreTrouvee = true %}
            <li class="flex flex-col card-offer">
                {% if offre.produits.images is not empty %}
                {% set image = offre.produits.images.first() %}
                <img src="{{ asset('uploads/images/' ~ offre.produits.images.first.nomImage) }}" height="auto"
                    width="80px" alt="Image de {{ image.nomImage }}">
                {% else %}
                <img src="{{ asset('uploads/images/defaut.jpg') }}" height="auto" width="80px" alt="Mon image" />
                {% endif %}

                <p>Produit : {{ offre.produits.nomProduit }}</p>
                <p>Prix proposé : {{ offre.prix }}€</p>
                <p>Prix initial : {{ offre.produits.prix }}€</p>
                <p>Statut : {{ offre.getStatutText() }}</p>
                {% if offre.statut == 1 %}
                <a href="{{ path('show_order', {id: offre.produits.id })}}">Paiement</a>
                {% endif %}
                {% if offre.getStatutText() == 2 %}

                {% endif %}
                <p><a href="{{ path('show_produit', { slug: offre.produits.slug }) }}">Voir le produit</a></p>
            </li>
            {% endif %}

            {% endfor %}
        </ul>
        {% endif %}

        {% if offres is not empty and not offreTrouvee %}
        <p>Aucune offre reçue.</p>
        {% endif %}
    </div>
</div>

templates/profil/_notif.html.twig
<div>
    <h2>Mes notifications</h2>

    <div class="relative">
        <div class="tabs">
            <div class="tab" id="tab-commandes">Commandes</div>
            <div class="tab" id="tab-notifs">Offres</div>
        </div>

        <div class="notifications">
            <div class="tab-content" id="content-commandes">
                <!-- Contenu des commandes -->
                {% if commandeAcheteur is not empty %}
                {% for commande in commandes %}
                {% if app.user == commande.produit.user and commande.produit.isSelling == true %}
                <p class="notification notif-vente">{{ commande.message }}</p>
                {% endif %}

                {% if app.user == commande.commander %}
                <p class="notification notif-vente">{{ commande.messageSent }}</p>
                {% endif %}

                {% endfor %}
                {% else %}
                <p class="notif-p">Aucune notification.</p>
                {% endif %}
            </div>
            <div class="tab-content" id="content-notifs">
                <!-- Contenu des notifications/offres -->
                {% if notifs is not empty %}
                {% for notif in notifs %}
                {% set bold = notif.isRead ? '' : 'bold' %}
                {% if app.user == notif.offre.produits.user %}
                <p class="notification {{ bold }}" data-notification-id="{{ notif.id }}">{{ notif.messageDestinataire }}
                </p>
                {% set hasDisplayedNotifications = true %}
                {% endif %}

                {% if app.user == notif.offre.Users %}
                <p class="notification {{ bold }}" data-notification-id="{{ notif.id }}">{{ notif.message }}</p>
                {% set hasDisplayedNotifications = true %}
                {% endif %}

                {% endfor %}
                {% else %}
                <p class="notif-p">Aucune notification.</p>
                {% endif %}
            </div>
        </div>
    </div>

</div>

templates/profil/_vendeur.html.twig
<div class="card-seller">
    <div>
        <h2>Espace vendeur</h2>
        <ul class="flex flex-col gap">
            <h3>Vos commandes</h3>
            {% if commandeVendeur is not empty %}
            {% for commande in commandeVendeur %}
            <li class="card-command flex gap05 wrap">
                {% if commande.produit.images is not empty %}
                <!--récupérer la 1er image uniquement -->
                {% set image = commande.produit.images.first() %}
                <img src="{{ asset('uploads/images/' ~ image.nomImage) }}" height="150px" width="100px"
                    alt="Image de {{ image.nomImage }}" />

                {% else %}
                <img src="{{ asset('uploads/images/defaut.jpg') }}" height="150px" width="100px" alt="Mon image" />
                {% endif %}
                <div class="grow mh-1 p-05-w">
                    <div class="flex justify-between wrap">
                        <p> {{ commande.produit.nomProduit }}</p>
                        <p>Prix: {{ commande.produit.prix}}€</p>
                    </div>
                    <div class="adresse-commande flex justify-between wrap">
                        <div>
                            Adresse de livraison du client:

                            <div class="flex gap05 wrap">
                                <p>Nom: {{ commande.nom}}</p>
                                <p>Prénom: {{ commande.prenom}}</p>
                            </div>
                            <div>
                                <p>Adresse: {{ commande.adresse}}</p>
                                <p>Ville: {{ commande.ville}}</p>
                                <p>Code postal: {{ commande.codePostal}}</p>
                            </div>
                        </div>
                        <div class="flex wrap gap05">
                            <p class="tooltip-container">Produit envoyé (?)
                                <span class="tooltip">Penser à cliquer sur le lien une fois le colis envoyer afin de
                                    prévenir le
                                    client.</span>
                            </p>
                            <div>

                                {% if commande.isSent == false %}
                                <a href="{{path('order_sent', {'id': commande.id })}}">
                                    <p style="color: red;">Non</p>
                                </a>
                                {% else %}
                                <p style="color: green;">Oui</p>
                                {% endif %}

                            </div>
                        </div>
                    </div>
                </div>
            </li>

            {% endfor %}
            {% else %}
            <p>Aucune commande en cours</p>
            {% endif %}
        </ul>
    </div>


    <div class="offer-container">
        <h3>Offre reçue</h3>
        {% set offreTrouvee = false %}
        {% if offresObtenu is empty %}
        <p>Aucune offre reçue.</p>
        {% else %}
        <ul class="flex wrap gap">
            {% for offre in offresObtenu %}
            {% if app.user == offre.produits.user %}
            {% set offreTrouvee = true %}
            <li class="flex flex-col card-offer">
                {% if offre.produits.images is not empty %}
                {% set image = offre.produits.images.first() %}
                <img src="{{ asset('uploads/images/' ~ offre.produits.images.first.nomImage) }}" height="auto"
                    width="80px" alt="Image de {{ image.nomImage }}">
                {% else %}
                <img src="{{ asset('uploads/images/defaut.jpg') }}" height="auto" width="80px" alt="Mon image" />
                {% endif %}
                <p>Produit : {{ offre.produits.nomProduit }}</p>
                <p>Prix proposé : {{ offre.prix }}€</p>
                <p>Prix initial : {{ offre.produits.prix }}€</p>
                <p>Statut : {{ offre.getStatutText() }}</p>
                {% if offre.statut == constant('App\\Entity\\Offre::STATUT_EN_ATTENTE') %}
                <a href="{{ path('changer_statut_offre', { id: offre.id, statut: 'acceptee' }) }}">Accepter</a>
                <a href="{{ path('changer_statut_offre', { id: offre.id, statut: 'refusee' }) }}">Refuser</a>
                {% endif %}
                <p><a href="{{ path('show_produit', { slug: offre.produits.slug }) }}">Voir le produit</a></p>
            </li>
            {% endif %}
            {% endfor %}
        </ul>
        {% endif %}

        {% if offresObtenu is not empty and not offreTrouvee %}
        <p>Aucune offre reçue.</p>
        {% endif %}
    </div>
</div>