src/Entity/Offre.php
<?php

namespace App\Entity;

use App\Repository\OffreRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: OffreRepository::class)]
class Offre
{
    public const STATUT_EN_ATTENTE = 0;
    public const STATUT_ACCEPTEE = 1;
    public const STATUT_REFUSEE = 2;

    public function getStatutText(): string
    {
        switch ($this->statut) {
            case self::STATUT_EN_ATTENTE:
                return 'En attente';
            case self::STATUT_ACCEPTEE:
                return 'Acceptée';
            case self::STATUT_REFUSEE:
                return 'Refusée';
            default:
                return 'Inconnu';
        }
    }

    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $prix = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, options: ["default" => "CURRENT_TIMESTAMP"])]
    private ?\DateTimeInterface $date = null;

    #[ORM\Column]
    private ?int $statut = null;

    #[ORM\ManyToOne(inversedBy: 'offres')]
    private ?Produit $produits = null;

    #[ORM\ManyToOne(inversedBy: 'offres')]
    private ?User $Users = null;

    #[ORM\Column]
    private ?bool $notifStatus = null;


    #[ORM\OneToMany(mappedBy: 'offre', targetEntity: Notification::class, orphanRemoval: true)]
    private Collection $notifications;

    #[ORM\Column]
    private ?bool $isDeleted = false;

    public function __construct()
    {
        $this->notifications = new ArrayCollection();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getStatut(): ?int
    {
        return $this->statut;
    }

    public function setStatut(int $statut): self
    {
        $this->statut = $statut;

        return $this;
    }

    public function getProduits(): ?Produit
    {
        return $this->produits;
    }

    public function setProduits(?Produit $produits): self
    {
        $this->produits = $produits;

        return $this;
    }

    public function getUsers(): ?User
    {
        return $this->Users;
    }

    public function setUsers(?User $Users): self
    {
        $this->Users = $Users;

        return $this;
    }

    public function isNotifStatus(): ?bool
    {
        return $this->notifStatus;
    }

    public function setNotifStatus(bool $notifStatus): self
    {
        $this->notifStatus = $notifStatus;

        return $this;
    }



    /**
     * @return Collection<int, Notification>
     */
    public function getNotifications(): Collection
    {
        return $this->notifications;
    }

    public function addNotification(Notification $notification): self
    {
        if (!$this->notifications->contains($notification)) {
            $this->notifications->add($notification);
            $notification->setOffre($this);
        }

        return $this;
    }

    public function removeNotification(Notification $notification): self
    {
        if ($this->notifications->removeElement($notification)) {
            // set the owning side to null (unless already changed)
            if ($notification->getOffre() === $this) {
                $notification->setOffre(null);
            }
        }

        return $this;
    }

    public function isIsDeleted(): ?bool
    {
        return $this->isDeleted;
    }

    public function setIsDeleted(bool $isDeleted): self
    {
        $this->isDeleted = $isDeleted;

        return $this;
    }
}

src/Controller/ProduitController.php
<?php

namespace App\Controller;


use Stripe\Stripe;
use App\Entity\Avis;
use App\Entity\User;
use App\Entity\Offre;
use App\Entity\Produit;
use App\Form\OffreType;
use App\Form\OrderType;
use App\Entity\Commande;
use App\Entity\Categorie;
use App\Entity\Notification;
use Symfony\Component\Mime\Email;
use App\Repository\AvisRepository;
use App\Repository\ProduitRepository;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\Persistence\ManagerRegistry;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class ProduitController extends AbstractController
{
    #[Route('/produit', name: 'app_produit')]
    public function index(): Response
    {
        return $this->render('produit/index.html.twig', [
            'controller_name' => 'ProduitController',
        ]);
    }

    #[Route('/produit/show/{slug}', name: 'show_produit')]
    public function show(ManagerRegistry $doctrine, Produit $produit = null, Request $request, PaginatorInterface $paginator, AvisRepository $av): Response
    {
        if ($produit === null) {
            // Si le produit n'existe pas, redirigez l'utilisateur vers une page d'erreur ou une autre page appropriée.
            return $this->redirectToRoute('app_home');
        }

        $user = $this->getUser();

        // Vérifiez si l'utilisateur est connecté avant d'accéder à $user
        if ($user !== null) {
            $vendeur = $produit->getUser(); // Récupérez le vendeur du produit
            $avis = $av->findBy(['Vendeur' => $vendeur], ["id" => "DESC"]);

            // Pagination de tous les avis
            $paginationAvis = $paginator->paginate(
                $avis,
                $request->query->get('page', 1),
                6
            );

            if ($produit->isIsSelling() == false && $produit->isEtat() == true) {
                return $this->render('produit/show.html.twig', [
                    'controller_name' => 'HomeController',
                    'produit' => $produit,
                    'avis' => $avis,
                    'paginations' => $paginationAvis,
                ]);
            }
        }

        // Redirigez l'utilisateur vers la page d'accueil par défaut
        return $this->redirectToRoute('app_home');
    }

    #[Route('/pagination/produit/show/{slug}', name: 'app_pagination_avis')] // pagination des produits
    public function pagination(ProduitRepository $produitRepository, Request $request, PaginatorInterface $paginator, AvisRepository $av): JsonResponse
    {
        // Récupérer la page demandée depuis la requête
        $page = $request->query->getInt('page', 1);
        // Récupérer le produit en fonction du slug
        $slug = $request->attributes->get('slug');
        $produit = $produitRepository->findOneBy(['slug' => $slug]);
        $vendeur = $produit->getUser(); // Récupérez le vendeur du produit
        $avis = $av->findBy(['Vendeur' => $vendeur], ["id" => "DESC"]);
        // Nombre d'articles à afficher par page
        $limit = 6;

        // Effectuer la recherche en utilisant les paramètres
        $pagination = $paginator->paginate(
            $avis,
            $page,
            $limit
        );

        // Renvoyer les résultats paginés au format HTML
        return $this->json([
            'resultProduct' => $this->renderView('produit/_avis_client.html.twig', [
                'paginations' => $pagination,
                'produit' => $produit, // Passer le produit à la vue partielle
            ])
        ]);
    }





    #[Route('/produit/order/{id}', name: 'show_order')] // vue de la commande
    public function showOrder(ManagerRegistry $doctrine,  Produit $produit = null, Request $request): Response
    {
        $user = $this->getUser();

        if (!$user) {
            return $this->redirectToRoute('app_login');
        }

        if ($produit) {

            $commande = new Commande;
            $form = $this->createForm(OrderType::class, $commande,  []);
            $form->handleRequest($request); // analyse the request

            if ($form->isSubmitted() && $form->isValid()) { // valid respecter les contraintes

                $commande = $form->getData();

                //$commande->setUser($user); // install mon user
                $now = new \DateTime(); // objet date
                $commande->setDateCommande($now); // installe ma date
                $commande->setCommander($user);
                $commande->setProduit($produit);
                $commande->setEtat(0);
                // Gérer le message de notification
                if ($produit->getNomProduit()) {
                    $notificationMessage = "Félicitation! Le produit : \"" . $produit->getNomProduit() . "\" a été vendu, merci de procéder rapidement à l'envoi.";
                } else {
                    $notificationMessage = "Félicitation! Un produit a été vendu, merci de procéder rapidement à l'envoi.";
                }
                $commande->setMessage($notificationMessage);
                $entityManager = $doctrine->getManager(); // on récupère les ressources
                $entityManager->persist($commande); // on enregistre la ressource
                $entityManager->flush(); // on envoie la ressource insert into

                return $this->redirectToRoute(
                    'app_test',
                    ['produitId' => $produit->getId()]
                );
            }



            return $this->render('produit/order.html.twig', [
                'controller_name' => 'HomeController',
                'produit' => $produit,
                'formCommande' => $form->createView(),

            ]);
        } else {
            return $this->redirectToRoute('app_home');
        }
    }

    #[Route('/produit/sent/{id}', name: 'order_sent')] // publier annonce
    //#[IsGranted('ROLE_ADMIN')]
    public function sentProduct(ManagerRegistry $doctrine, Commande $commande, MailerInterface $mailer)
    {


        if ($commande->isIsSent()) {
            $commande->setIsSent(false);
        } else {
            $commande->setIsSent(true);
            $commande->setMessageSent("Votre commande concernant \"" . $commande->getProduit()->getNomProduit() . "\" à bien été envoyé.");

            $clientEmail = $commande->getCommander()->getEmail();
            $produitNom = $commande->getProduit()->getNomProduit();
            $nomVendeur = $commande->getProduit()->getUser()->getPseudo();
            $email = (new Email())
                ->from('admin@worldofpets.com')
                ->to($clientEmail)
                ->subject("WorlfofPets - Votre colis \"" . $produitNom . "\" a bien été envoyé")
                ->text("Le colis $produitNom. a été envoyé par " . $nomVendeur .  ".  L'équipe WorldofPets");

            $mailer->send($email);
        }

        $em = $doctrine->getManager();
        $em->flush();

        return $this->redirectToRoute('show_home');
    }

    #[Route('/produit/received/{id}', name: 'order_received')] // publier annonce
    //#[IsGranted('ROLE_ADMIN')]
    public function receivedProduct(ManagerRegistry $doctrine, Commande $commande, MailerInterface $mailer)
    {


        if ($commande->isIsReceived()) {
            $commande->setIsReceived(false);
        } else {
            $commande->setIsReceived(true);
            //$commande->setMessageSent("Votre commande concernant \"" . $commande->getProduit()->getNomProduit() . "\" à bien été envoyé.");

            $clientEmail = $commande->getProduit()->getUser()->getEmail();
            $produitNom = $commande->getProduit()->getNomProduit();
            $nomVendeur = $commande->getProduit()->getUser()->getPseudo();
            $email = (new Email())
                ->from('admin@worldofpets.com')
                ->to($clientEmail)
                ->subject("WorlfofPets - Colis \"" . $produitNom . "\"  receptionné")
                ->text("Votre colis $produitNom a bien été receptionné par l'acheteur.  L'équipe WorldofPets");

            $mailer->send($email);
        }

        $em = $doctrine->getManager();
        $em->flush();

        return $this->redirectToRoute('show_home');
    }

    #[Route('/offre/{vendorId}/{productId}', name: 'show_offre')] // formulaire offre 
    public function send(Request $request, ManagerRegistry $doctrine, $vendorId, $productId, MailerInterface $mailer): Response
    {
        $user = $this->getUser();
        $offre = new Offre();

        if (!$user) {
            return $this->redirectToRoute('app_login');
        }

        $produit = $doctrine->getRepository(Produit::class)->find($productId);
        $offreRepository = $doctrine->getRepository(Offre::class);

        // Vérifier si l'utilisateur a déjà fait une offre pour ce produit
        $existingOffre = $offreRepository->findOneBy(['Users' => $user, 'produits' => $produit]);
        $offreIsDeleted = $offreRepository->findOneBy([]);
        //dd($existingOffre);

        // Vérifier si une offre a été acceptée pour ce produit
        $offreAcceptee = $offreRepository->findOneBy(['produits' => $produit, 'statut' => Offre::STATUT_ACCEPTEE]);

        if ($offreAcceptee) {
            $this->addFlash('error', 'Une offre a déjà été acceptée pour ce produit.');
            return $this->redirectToRoute('show_home');
        }

        if ($existingOffre && $existingOffre->isIsDeleted() === false) {
            $this->addFlash('error', 'Une offre existe déjà pour ce produit.');

templates/produit/_avis_client.html.twig
<h2 class="text-center">Avis clients</h2>

<div class="flex justify-center gap items-center wrap">
    <figure>
        {% set image = produit.images.first() %}
        {% if image is defined and image is not empty %}
        <img src="{{ asset('uploads/images/' ~ image.nomImage) }}" height="200" width="200px"
            alt="Image de {{ image.nomImage }}">
        {% else %}
        <img src="{{ asset('uploads/images/defaut.jpg') }}" height="200px" width="200px" alt="Mon image">
        {% endif %}
    </figure>
    <div class="text-center">
        <p>Voir le profil du vendeur:
            <a href="{{path('show_avis', {'vendorId': produit.user.id })}}">Par ici</a>
        </p>
        <!--<p class="avis">Avis vendeur : </p>
        <a href="{{path('add_avis', {'vendorId': produit.user.id })}}" class="btn-menu btn-pad">Donné nous votre avis
            !</a>-->
    </div>
</div>
<div>

    <ul class="container-avis">
        {% set hasComments = false %}
        {% for commentaire in paginations %}

        {% if produit.user == commentaire.vendeur %}
        {% set hasComments = true %}
        <li class="comment-product">
            <div class="flex justify-between">
                <p>De {{commentaire.users}}</p>
                <p>{{commentaire.dateAvis | date('d/m/Y H:i:s')}}</p>
            </div>
            <p>Note :
                {% for i in 1..5 %}
                {% if i <= commentaire.note %} <i class="fa fa-star fa-star-filled"></i>
                    {% else %}
                    <i class="fa-regular fa-star fa-star-filled"></i>
                    {% endif %}
                    {% endfor %}
            </p>
            <p>{{ commentaire}}</p>
            {% if app.user == commentaire.users.pseudo %}
            <p class="text-right"><a
                    href="{{path('delete_avis', {'id': commentaire.id, 'vendorId': commentaire.vendeur.id })}}"><i
                        class="fa-sharp fa-solid fa-trash"></i></a></p>
            {% endif %}

            <!--{% if app.user == commentaire.vendeur %}
        <p><a href="{{ path('add_reply', {'vendorId': commentaire.vendeur.id, 'parentId': commentaire.id}) }}"
                class="btn" data-reply data-id="{{ commentaire.id }}">Répondre</a></p>
        {% endif %} -->


            <!-- Affichage des réponses -->
            {% for reply in commentaire.getReponse() %}
            {% if reply.actif == true %}
            <ul class="reply">
                <li class="comment">
                    <div class="flex justify-between">
                        <p>De {{reply.users}}</p>
                        <p>{{reply.dateAvis | date('d/m/Y H:i:s')}}</p>
                    </div>
                    <p>{{ reply.commentaire }}</p>

                    {% if reply.users.pseudo == app.user %}
                    <p class="text-right"><a
                            href="{{path('delete_reply', { 'vendorId': reply.vendeur.id, 'parentId' : reply.id})}}"><i
                                class="fa-sharp fa-solid fa-trash"></i></a></p>
                    {% endif %}


                </li>
                <!-- Affichez les autres informations de la réponse -->
            </ul>

            {% endif %}

            {% endfor %}
        </li>
        {% endif %}

        {% endfor %}
    </ul>

    {% if hasComments %}
    {{knp_pagination_render(paginations)}}
    {% endif %}




</div>

templates/produit/_detail_produit.html.twig
<div id="product-detail">
    <div class="info-product">
        <h2>{{produit}}</h2>
        <p>Categorie : <a href="{{path('show_categorie', {'slug': produit.categorie.slug })}}">{{
                produit.categorie.nomCategorie }}</a></p>
        <p>Etat : {{ produit.statut }}</p>
        <p>Vendeur : <a href="{{path('show_user', {'id': produit.user.id })}}">{{ produit.user.pseudo }}</a></p>
        <p>Avis vendeur : </p>
        <p>Description : {{ produit.description }}</p>
        <!-- <p class="stock">Stock : {{ produit.disponible }}</p> -->
        <p class="price">Prix : {{ produit.prix }} €</p>
        <ul class="flex wrap gap mh-2">
            <li>
                <a href="{{path('show_order', {'id': produit.id } )}}" class="btn-menu">Acheter</a>
            </li>

            <li>
                <a href="{{ path('show_offre', {'vendorId': produit.user.id, 'productId': produit.id })}}"
                    class="btn-menu">Faire une offre</a>
            </li>

            <li>
                <a href="{{path('send', {'vendorId': produit.user.id })}}" class="btn-menu">Contacter le vendeur</a>
            </li>
        </ul>
    </div>
    <div>
        <div style="--swiper-navigation-color: #fff; --swiper-pagination-color: #fff"
            class="swiper mySwiper12 img-slide">
            <div class="swiper-wrapper">
                {% for image in produit.images %}
                <div class="swiper-slide image-container">
                    <a href="{{ asset('uploads/images/' ~ image.nomImage) }}" data-lightbox="{{ image.nomImage }}"
                        class="w-100" data-title="World of pets - {{ image.produit.nomProduit }}">
                        <img src="{{ asset('uploads/images/' ~ image.nomImage) }}" data-action="zoom"
                            alt="World of pets - {{ image.produit.nomProduit }}">
                    </a>
                </div>
                {% endfor %}
            </div>
            <div class="swiper-button-next"></div>
            <div class="swiper-button-prev"></div>
        </div>
        <div thumbsSlider="" class="swiper2 mySwiper15 img-little-slide">
            <div class="swiper-wrapper">
                {% for image in produit.images %}
                <div class="swiper-slide">
                    <img src="{{ asset('uploads/images/' ~ image.nomImage) }}" data-action="zoom"
                        alt="Image de {{ image.nomImage }}">
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
<!-- Initialize Swiper -->
<script>
    var swiper = new Swiper(".mySwiper15", {
        spaceBetween: 10,
        slidesPerView: 4,
        freeMode: true,
        watchSlidesProgress: true,
    });
    var swiper12 = new Swiper(".mySwiper12", {
        spaceBetween: 10,
        navigation: {
            nextEl: ".swiper-button-next",
            prevEl: ".swiper-button-prev",
        },
        thumbs: {
            swiper: swiper,
        },
    });
</script>

templates/produit/_other_product.html.twig
<div class="other-product-container">
    <div>
        <h2 class="text-center">Articles qui pourrait vous interessé</h2>
    </div>
    <div class="swiper mySwiper99 bg-white">
        <div class="swiper-wrapper">
            {% for produitCategorie in produit.categorie.produits %}

            {% if produitCategorie.etat == true and produitCategorie.id != produit.id %} {# afficher si produit
            valider
            #}
            <div class="swiper-slide bg-white">
                <a href="{{ path('show_produit',{'slug':produitCategorie.slug })}}">
                    <figure class="card-other-product">
                        {% if produitCategorie.images is not empty %} {# si il y a une image #}

                        <!--récupérer la 1er image uniquement -->
                        {% set image = produitCategorie.images.first() %}
                        <img src="{{ asset('uploads/images/' ~ image.nomImage) }}" height="200" width="200px"
                            alt="Image de {{ image.nomImage }}">


                        {% else %}
                        <img src="{{ asset('uploads/images/defaut.jpg') }}" height="200px" width="200px"
                            alt="Mon image">
                        {% endif %}
                        <figcaption>
                            <p>{{ produitCategorie.nomProduit }}</p>
                            <p>{{ produitCategorie.prix }} €</p>
                        </figcaption>
                    </figure>
                </a>
            </div>
            {% endif %}
            {% endfor %}
        </div>
        <div class="swiper-button-next"></div>
        <div class="swiper-button-prev"></div>
        <div class="swiper-pagination"></div>
    </div>
</div>

templates/produit/add.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter votre article{% endblock %}

{% block javascripts %}
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const file_upload = document.querySelector('#produit_images');
        file_upload.addEventListener('change', previewFile);

        function previewFile() {
            const file_extension_regex = /\.(jpe?g|png|gif)$/i;
            if (this.files.length === 0) {
                return;
            }
            const files = Array.from(this.files).filter(file => file_extension_regex.test(file.name));

            const container = document.querySelector('#images-preview');
            container.innerHTML = ''; // vider le contenu existant

            for (const file of files) {
                const file_reader = new FileReader();

                file_reader.readAsDataURL(file);

                file_reader.addEventListener('load', (event) => displayImage(event, file, container));
            }
        }

        function displayImage(event, file, container) {
            const figure_element = document.createElement('figure');
            figure_element.id = "image_selected";

            const image_element = document.createElement('img');
            image_element.src = event.target.result;

            // définir une taille pour l'image
            image_element.style.width = "200px";
            image_element.style.height = "250px";

            figure_element.appendChild(image_element);
            container.appendChild(figure_element);
        }

    });
</script>
{% endblock javascripts %}

{% block body %}
{% if edit %}
<h1>Modifier l'annonce</h1>
<p style="color:red;" class="text-center"><i class="fa-sharp fa-solid fa-triangle-exclamation fa-lg"></i> Attention ! En
    cas de
    modification, l'annonce n'apparaîtra plus et devra être validé par nos services. </p>
{% else %}
<h1>Ajouter produit</h1>
{% endif %}


<div id="product-container">

    {% if app.user %}



    {{ form_start(formAddProduit) }}

    <div id="images-preview"></div>
    {% for image in produits.images %}
    <div>
        <img src="{{ asset('uploads/images/' ~ image.nomImage) }}" height="auto" width="300px"
            alt="Image de {{ image.nomImage }}">
        <a href="{{path('delete_image', {'id': image.id })}}" data-delete
            data-token="{{csrf_token('delete' ~ image.id)}}">Supprimer</a>
    </div>
    {% endfor %}




    <div class="image-product">
        <p class="images-legende">Ajoute une ou plusieurs photos.</p>
        {{ form_row(formAddProduit.images) }}
    </div>
    {{ form_row(formAddProduit.nomProduit) }}
    {{ form_row(formAddProduit.description) }}
    {{ form_row(formAddProduit.categorie) }}
    {{ form_row(formAddProduit.prix) }}
    {{ form_row(formAddProduit.statut, {'attr': {'onchange': "this.children[0].disabled=true", 'data-placeholder':
    'Sélectionnez une catégorie', 'class' : 'grey-color'}}) }}
    <div class="product-valid">
        {{ form_row(formAddProduit.Valider, {'attr': {'class': 'btn' }}) }}
    </div>
    {{ form_end(formAddProduit) }}

    {% if app.flashes('error') is not empty %}
    <div class="alert alert-danger">
        {% for message in app.flashes('error') %}
        {{ message }}
        {% endfor %}
    </div>

    {% endif %}

    {% else %}

    <p>Vous devez vous connectez pour pouvoir vendre un produit.</p>

    {% endif %}
</div>



{% endblock %}

templates/produit/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProduitController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/laragon/www/Sf_petShop/src/Controller/ProduitController.php'|file_link(0) }}">src/Controller/ProduitController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/laragon/www/Sf_petShop/templates/produit/index.html.twig'|file_link(0) }}">templates/produit/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/produit/offre.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter votre article{% endblock %}

{% block javascripts %}
<script>
    document.addEventListener("DOMContentLoaded", function () {
        const file_upload = document.querySelector('#produit_images');
        file_upload.addEventListener('change', previewFile);

        function previewFile() {
            const file_extension_regex = /\.(jpe?g|png|gif)$/i;
            if (this.files.length === 0) {
                return;
            }
            const files = Array.from(this.files).filter(file => file_extension_regex.test(file.name));

            const container = document.querySelector('#images-preview');
            container.innerHTML = ''; // vider le contenu existant

            for (const file of files) {
                const file_reader = new FileReader();

                file_reader.readAsDataURL(file);

                file_reader.addEventListener('load', (event) => displayImage(event, file, container));
            }
        }

        function displayImage(event, file, container) {
            const figure_element = document.createElement('figure');
            figure_element.id = "image_selected";

            const image_element = document.createElement('img');
            image_element.src = event.target.result;

            // définir une taille pour l'image
            image_element.style.width = "200px";
            image_element.style.height = "250px";

            figure_element.appendChild(image_element);
            container.appendChild(figure_element);
        }

    });
</script>
{% endblock javascripts %}

{% block body %}


<div class="container-offre height-form-offre">
    <h1>Faite votre offre</h1>
    {% if app.user %}
    <div class="offre-form">
        {{ form_start(form) }}
        <div class="flex">{{ form_row(form.prix) }}</div>
        {{ form_end(form) }}
    </div>
</div>

{% else %}

<p>Vous devez vous connectez pour pouvoir vendre un produit.</p>

{% endif %}




{% endblock %}

templates/produit/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Produit : {{ produit }}{% endblock %}

{% block body %}
<div id="cat-container">
    {% if produit.imageShow is not null %}
    <figure>
        <img src="{{ produit.imageShow }}" alt="chien" width="100%" height="400px">
    </figure>
    {% endif %}
    <h1>Produit détaillé : {{ produit }}</h1>
</div>

{% include "produit/_detail_produit.html.twig" %}

<section id="avis-container">
    {% include "produit/_avis_client.html.twig" %}
</section>
{% if produit.categorie.produits is not empty %}

{% include "produit/_other_product.html.twig" %}

{% endif %}



<script>
    var swiper = new Swiper(".mySwiper99", {
        slidesPerView: 1,
        spaceBetween: 30,
        pagination: {
            el: ".swiper-pagination",
            clickable: true,
        },
        navigation: {
            nextEl: ".swiper-button-next",
            prevEl: ".swiper-button-prev",
        },
        breakpoints: {
            // Lorsque la largeur de l'écran est supérieur ou égale à 768 pixels (mobile)
            768: {
                slidesPerView: 2, // Une seule diapositive sur mobile
            },
            // Lorsque la largeur de l'écran est supérieure à 768 pixels mais inférieure ou égale à 1024 pixels (tablette)
            1024: {
                slidesPerView: 3, // Deux diapositives sur tablette
            },
            1250: {
                slidesPerView: 4, // Deux diapositives sur tablette
            },
        },
    });
</script>
<script src="{{asset('js/zoom.js')}}"></script>
<script src="{{asset('js/paginationAvis.js')}}"></script>
{% endblock %}